version: '3'

services:
    go-server:
        container_name: 'go-server'
        build:
            context: .
        volumes: 
            - ./:/app
        ports:
            - 8080:8080
    web-server:
        image: nginx
        volumes:
            - ./:/usr/share/nginx/html
        ports:
            - 8050:80